### ISSUE TITLE
Where's the history? 

### ISSUE THREAD

**Issue by igalic** [bsdci/ioc#1]
There's tools in git to extract a subtree from a project into a new repo — while retaining the history.

Perhaps we should do that, rather than have a fake blank start.

**Comment by igalic** [comment]
it's called `git-subtree` and here's a step by step howto https://lostechies.com/johnteague/2014/04/04/using-git-subtrees-to-split-a-repository/

**Comment by gronke** [comment]
Good call! Moved the copy attempt to a [copy branch](https://github.com/bsdci/ioc/tree/copy) and pushed the subtree including the history to master.
