### ISSUE TITLE
ioc is in FreeBSD ports now, but misses jail module

### ISSUE THREAD

**Issue by netchild** [bsdci/ioc#41]
Hi,

ioc is now in FreeBSD ports, so partly the ioc website is wrong stating that it is not there, but partly right, as it is not working.

Test with iocage jails running but iocage being deinstalled and right after ioc was installed:
> ioc list
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 13, in <module>
    from ioc_cli import cli
  File "/usr/local/lib/ioc/ioc_cli/__init__.py", line 43, in <module>
    from libioc.Datasets import Datasets
  File "/usr/local/lib/python3.6/site-packages/libioc/Datasets.py", line 31, in <module>
    import libioc.helpers
  File "/usr/local/lib/python3.6/site-packages/libioc/helpers.py", line 37, in <module>
    import jail as libjail
ModuleNotFoundError: No module named 'jail'

So this is a bug report that there is a py-jail missing in the FreeBSD ports.

Bye,
Alexander.

**Comment by gronke** [comment]
Hi @netchild, thanks for reporting this issue! Indeed the machines I have tested on had the pip dependencies installed. On a clean Digital Ocean droplet, I was able to confirm this issue.

The quick workaround to get the missing Python dependencies installed is to run:

```
python3.6 -m pip install jail freebsd-sysctl  
```

I will create ports for both Python modules `jail` and `freebsd_sysctl`, that can then be added as dependency to the devel/py-libioc port.

**Comment by igalic** [comment]
it simply took so long between creating the bug for the port, and the port being merged that… ***this*** happened

**Comment by netchild** [comment]
Send me the PR, or add me to the watch list of the PR. If there is not too much python related stuff in the port (so that I can compare it to the ioc port), I take care that it hits the tree faster,

**Comment by gronke** [comment]
@netchild here are the FreeBSD Bugs for the new ports:

- https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240920
- https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240921

I've put you on the list of subscribers.

**Comment by netchild** [comment]
Belatedly... this was committed to FreeBSD a while ago...
