### ISSUE TITLE
ioc -d non-existent-log-level is taken, as-is.

### ISSUE THREAD

**Issue by igalic** [bsdci/ioc#8]
When calling `ioc -d` with an inexistent log level, we should error out, printing a list of existing log levels.

**Comment by gronke** [comment]
That's already the case:

```console
$ python3.6 . -d foo list
Invalid log-level foo. Choose one of critical, error, warn, info, notice, verbose, debug, spam or screen
```

**Comment by igalic** [comment]
hrm… so it only appears when the (invalid) loglevel we supply is a valid sub-command

**Comment by igalic** [comment]
so, what happens here?

```
ioc -d list start jail1
```
